### ISSUE TITLE
Ansible ssh problem?

### ISSUE THREAD

**Issue by ajs6f** [UMD-DRASTIC/drastic-deploy#1]
Hi, DRAS-TIC folks! I'm trying to bring up a local instance to do a bit of test driving, and running into:

```
PLAY [Install a complete Drastic instance] *************************************

TASK [Gathering Facts] *********************************************************
fatal: [node-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2200' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
fatal: [node-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/Users/ajs6f/Documents/drastic/drastic-deploy/deploy_standalone.retry

PLAY RECAP *********************************************************************
node-1                     : ok=0    changed=0    unreachable=1    failed=0
node-2                     : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
Looks like some kind of problem with Ansible trying to call back to the host? Do I need to do some kind of key copying or the like?

If it is of relevance, I'm on Mac OS X 10.12.5, Vagrant 1.9.5, Ansible 2.3.0.0. Thanks for any help!

**Comment by gregjan** [comment]
Hmm, yeah well it seems to do the 1st handshake for SSH, but then fail the auth step. Can you try an:

    $ ansible all -m ping

(In fact, you are within vagrant here.. So this may not work. Can you paste the full console somewhere?)

**Comment by ajs6f** [comment]
Right on-- see https://gist.github.com/ajs6f/351cec7af6113b6b9773099c92d000f4

As you'll see, I wasn't sure where you meant for me to try `ansible all -m ping`, so I tried inside and outside a vagrant node...

**Comment by gregjan** [comment]
Oh wait, this is ansible as executed by multi-machine vagrant. Generally I find that the difference between Mac and Ubuntu vagrant (and vbox vs kvm) is the NAT or virtual network. In this case it may even be down to a mismatch between the hostnames used by ansible and those generated by Vagrant (vbox in your case). If you look over at the [Vagrantfile](https://github.com/UMD-DRASTIC/drastic-deploy/blob/master/Vagrantfile#L21), you will see that the hostnames are supposed to be "db1", "db2", and "web". However, in the inline ansible inventory, they are references as node-1, node-2, and node-3.
I think node.vm.hostname may be working on vbox, whereas it didn't work on kvm. Maybe try commenting out the node.vm.hostname lines and see what happens..

**Comment by ajs6f** [comment]
Nope, still
```
PLAY [Install a complete Drastic instance] *************************************

TASK [Gathering Facts] *********************************************************
fatal: [node-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
fatal: [node-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:2200' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/Users/ajs6f/Documents/drastic/drastic-deploy/deploy_standalone.retry

PLAY RECAP *********************************************************************
node-1                     : ok=0    changed=0    unreachable=1    failed=0
node-2                     : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I'm wondering if there is something goofy about my workstation. If you have successfully used this on Ubuntu (I think that's what you said) then maybe I will try a double-nest, spinning up an Ubuntu box and within it, spinning up this?

**Comment by gregjan** [comment]
Ha! Certainly a fun idea. I wonder how recursive those Ubuntu virtual machine optimizations are?

**Comment by ajs6f** [comment]
I am going to find out tomorrow. Further bulletins as events warrant.

**Comment by gregjan** [comment]
You could also comment out the ansible play itself and inspect the machines and their hostnames/connections. That's what I would do. I had some network snooping to do in order to get the multi-machine ansible play to work in the first place. I really appreciate your efforts. You are the first to try this.

**Comment by gregjan** [comment]
Fixed! You can see the resolution in the commit, but it boils down to an ansible variable that was forcing the remote user to be "vagrant" instead of "ubuntu". Had to track down the ansible inventory that vagrant generates and compare it with the debug output of ansible when running in vagrant (setting ansible.debug_output = "vvvv")..  Noticed that inside of vagrant provision ansible was using 'vagrant' as the username, but in the inventory it was supposed to use 'ubuntu'.. This took a while to track down. Still work in libvirt/KVM as well.
